# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # --- FRONTEND DEPENDENCIES ---
  - package-ecosystem: "bun"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
    groups: # Group all npm updates together
      bun-dependencies:
        patterns:
          - "*"
    labels:
      - "bun"
      - "dependencies"
      - "dependabot"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(frontend/deps)"
      prefix-development: "chore(frontend/dev-deps)"
    ignore: # Ignore major version updates for now
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # --- BACKEND DEPENDENCIES ---
  - package-ecosystem: "gomod"
    directory: "/backend/"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"
    labels:
      - "go"
      - "dependencies"
      - "dependabot"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(backend/deps)"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # --- DOCKER IMAGES ---
  - package-ecosystem: "docker"
    directories: ["/backend/", "/frontend/"]
    schedule:
      interval: "weekly"
    groups:
      docker-images:
        patterns:
         - "*"
    labels:
      - "docker"
      - "dependabot"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(docker)"

  # --- DOCKER COMPOSE SCRIPTS ---
  - package-ecosystem: "docker-compose"
    directories: ["*"]
    schedule:
      interval: "weekly"
    groups:
      docker-images:
        patterns:
         - "*"
    labels:
      - "docker-compose"
      - "dependabot"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(docker-compose)"
